# Generated by Django 4.0.2 on 2022-02-27 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_orderupdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderupdate',
            old_name='oder_id',
            new_name='order_id',
        ),
    ]
